name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: xcode-xlsx
        path: .build/release

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: xcode-xlsx
        path: .build/release  
